# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger: none

stages:
- stage: Build
  jobs: 
  - job: Build

    pool:
      name: 'Default'

    variables:
      solution: 'NewWebApp/*.sln'
      buildPlatform: 'Any CPU'
      buildConfiguration: 'Release'

    steps:
    - task: NuGetToolInstaller@1

    - task: NuGetCommand@2
      inputs:
        restoreSolution: '$(solution)'

    - task: VSBuild@1
      inputs:
        solution: '$(solution)'
        msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'

    - task: VSTest@2
      inputs:
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'

- stage: DeployToDev
  jobs:
  - deployment: DeployToDev
    displayName: Deploy To Dev
    environment: 
      name: DEV
      resourceType: VirtualMachine
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadBuildArtifacts@0
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'drop'
              downloadPath: '$(System.ArtifactsDirectory)'

          - task: IISWebAppManagementOnMachineGroup@0
            inputs:
              IISDeploymentType: 'IISWebsite'
              ActionIISWebsite: 'CreateOrUpdateWebsite'
              WebsiteName: 'NewWebAppDev'
              WebsitePhysicalPath: '%SystemDrive%\inetpub\wwwroot\Websites\DEV\NewWebApp'
              WebsitePhysicalPathAuth: 'WebsiteUserPassThrough'
              AddBinding: true
              Bindings: 
                  '{
                      bindings:[
                          {
                              "protocol":"http",
                              "ipAddress":"*",
                              "hostname":"10.0.2.7",
                              "port":"96",
                              "sslThumbprint":"",
                              "sniFlag":false
                          }
                      ]
                  }'
              CreateOrUpdateAppPoolForWebsite: true
              AppPoolNameForWebsite: 'NewWebAppPoolDev'
              DotNetVersionForWebsite: 'v4.0'
              PipeLineModeForWebsite: 'Integrated'
              AppPoolIdentityForWebsite: 'SpecificUser'
              AppPoolUsernameForWebsite: 'domain\username'
              AppPoolPasswordForWebsite: 'password'
          
          - task: IISWebAppDeploymentOnMachineGroup@0
            inputs:
              WebSiteName: 'NewWebAppDev'
              Package: '$(System.ArtifactsDirectory)/drop/NewWebApp.zip'
              TakeAppOfflineFlag: true

- stage: DeployToQA
  jobs:
  - deployment: DeployToQA
    displayName: Deploy To QA
    environment: 
      name: QA
      resourceType: VirtualMachine
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadBuildArtifacts@0
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'drop'
              downloadPath: '$(System.ArtifactsDirectory)'

          - task: IISWebAppManagementOnMachineGroup@0
            inputs:
              IISDeploymentType: 'IISWebsite'
              ActionIISWebsite: 'CreateOrUpdateWebsite'
              WebsiteName: 'NewWebAppQA'
              WebsitePhysicalPath: '%SystemDrive%\inetpub\wwwroot\Websites\QA\NewWebApp'
              WebsitePhysicalPathAuth: 'WebsiteUserPassThrough'
              AddBinding: true
              Bindings: 
                  '{
                      bindings:[
                          {
                              "protocol":"http",
                              "ipAddress":"*",
                              "hostname":"10.0.2.5",
                              "port":"97",
                              "sslThumbprint":"",
                              "sniFlag":false
                          }
                      ]
                  }'
              CreateOrUpdateAppPoolForWebsite: true
              AppPoolNameForWebsite: 'NewWebAppPoolQA'
              DotNetVersionForWebsite: 'v4.0'
              PipeLineModeForWebsite: 'Integrated'
              AppPoolIdentityForWebsite: 'SpecificUser'
              AppPoolUsernameForWebsite: 'domain\username'
              AppPoolPasswordForWebsite: 'password'
          
          - task: IISWebAppDeploymentOnMachineGroup@0
            inputs:
              WebSiteName: 'NewWebAppQA'
              Package: '$(System.ArtifactsDirectory)/drop/NewWebApp.zip'
              TakeAppOfflineFlag: true

- stage: DeployToProd
  jobs:
  - deployment: DeployToProd
    displayName: Deploy To Prod
    environment: 
      name: PROD
      resourceType: VirtualMachine
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadBuildArtifacts@0
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'drop'
              downloadPath: '$(System.ArtifactsDirectory)'

          - task: IISWebAppManagementOnMachineGroup@0
            inputs:
              IISDeploymentType: 'IISWebsite'
              ActionIISWebsite: 'CreateOrUpdateWebsite'
              WebsiteName: 'NewWebAppProd'
              WebsitePhysicalPath: '%SystemDrive%\inetpub\wwwroot\Websites\Prod\NewWebApp'
              WebsitePhysicalPathAuth: 'WebsiteUserPassThrough'
              AddBinding: true
              Bindings: 
                  '{
                      bindings:[
                          {
                              "protocol":"http",
                              "ipAddress":"*",
                              "hostname":"10.0.2.4",
                              "port":"98",
                              "sslThumbprint":"",
                              "sniFlag":false
                          }
                      ]
                  }'
              CreateOrUpdateAppPoolForWebsite: true
              AppPoolNameForWebsite: 'NewWebAppPoolProd'
              DotNetVersionForWebsite: 'v4.0'
              PipeLineModeForWebsite: 'Integrated'
              AppPoolIdentityForWebsite: 'SpecificUser'
              AppPoolUsernameForWebsite: 'domain\username'
              AppPoolPasswordForWebsite: 'password'
          
          - task: IISWebAppDeploymentOnMachineGroup@0
            inputs:
              WebSiteName: 'NewWebAppProd'
              Package: '$(System.ArtifactsDirectory)/drop/NewWebApp.zip'
              TakeAppOfflineFlag: true